// API Settings
export const SET_API_SETTINGS_URL = 'SET_API_SETTINGS_URL';
export const SET_API_SETTINGS_TOKEN = 'SET_API_SETTINGS_TOKEN';
export const RESET_API_SETTINGS = 'RESET_API_SETTINGS';

// Model
export const SET_MODEL_DESCRIPTION = 'SET_MODEL_DESCRIPTION';
export const RESET_MODEL_DESCRIPTION = 'RESET_MODEL_DESCRIPTION';
export const UPDATE_FILTER_STRING = 'UPDATE_FILTER_STRING';
export const UPDATE_FILTER_PARAMETERS = 'UPDATE_FILTER_PARAMETERS';
export const UPDATE_FILTER_CONSTANTS = 'UPDATE_FILTER_CONSTANTS';
export const UPDATE_FILTER_INPUTS = 'UPDATE_FILTER_INPUTS';
export const UPDATE_FILTER_OUTPUTS = 'UPDATE_FILTER_OUTPUTS';
export const UPDATE_FILTER_CONTINUOUS = 'UPDATE_FILTER_CONTINUOUS';